# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 13:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('school', models.CharField(choices=[('1', 'Instituto Cumbres Bosques'), ('2', 'Instituto Cumbres Mexico'), ('3', 'Instituto Irlandes'), ('4', 'Instituto Cumbres Lomas')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Kids',
                'verbose_name': 'Kid',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('school', models.CharField(choices=[('1', 'Instituto Cumbres Bosques'), ('2', 'Instituto Cumbres Mexico'), ('3', 'Instituto Irlandes'), ('4', 'Instituto Cumbres Lomas')], max_length=50)),
                ('my_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Teams',
                'verbose_name': 'Team',
            },
        ),
        migrations.AddField(
            model_name='kid',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='school.Team'),
        ),
    ]
