# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('school', models.CharField(choices=[('1', 'Instituto Cumbres Bosques'), ('2', 'Instituto Cumbres Mexico'), ('3', 'Instituto Irlandes'), ('4', 'Instituto Cumbres Lomas')], max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='school.Team')),
            ],
            options={
                'verbose_name_plural': 'Leaders',
                'verbose_name': 'Leader',
            },
        ),
    ]
