# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='school',
        ),
    ]
