# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_kid_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('assistance', models.BooleanField(default=False)),
                ('week_talk', models.BooleanField(default=False)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Kid')),
            ],
            options={
                'verbose_name': 'Bitacora',
                'verbose_name_plural': 'Bitacoras',
            },
        ),
        migrations.AlterField(
            model_name='leader',
            name='school',
            field=models.CharField(choices=[('Instituto Cumbres Bosques', 'Instituto Cumbres Bosques'), ('Instituto Cumbres Mexico', 'Instituto Cumbres Mexico'), ('Instituto Irlandes', 'Instituto Irlandes'), ('Instituto Cumbres Lomas', 'Instituto Cumbres Lomas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='school',
            field=models.CharField(choices=[('Instituto Cumbres Bosques', 'Instituto Cumbres Bosques'), ('Instituto Cumbres Mexico', 'Instituto Cumbres Mexico'), ('Instituto Irlandes', 'Instituto Irlandes'), ('Instituto Cumbres Lomas', 'Instituto Cumbres Lomas')], max_length=50),
        ),
    ]
