# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20160412_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team_name',
        ),
        migrations.AddField(
            model_name='team',
            name='grade',
            field=models.CharField(choices=[('Sexto', 'Sexto de Primaria'), ('Primero', 'Primero de Secundaria'), ('Segundo', 'Segundo de Secundaria'), ('Tercero', 'Tercero de Secundaria'), ('Cuarto', 'Cuarto de Preparatoria')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
