# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20160411_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='/profile_pic'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='school',
            field=models.CharField(blank=True, choices=[('', ''), ('', ''), ('', '')], max_length=30),
        ),
    ]
