# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20160412_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='school',
            field=models.CharField(blank=True, choices=[('1', 'Instituto Cumbres Bosques'), ('2', 'Instituto Cumbres Mexico'), ('3', 'Instituto Irlandes'), ('4', 'Instituto Cumbres Lomas')], max_length=30),
        ),
    ]
