# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20160412_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='school',
            field=models.CharField(blank=True, choices=[('Instituto Cumbres Bosques', 'Instituto Cumbres Bosques'), ('Instituto Cumbres Mexico', 'Instituto Cumbres Mexico'), ('Instituto Irlandes', 'Instituto Irlandes'), ('Instituto Cumbres Lomas', 'Instituto Cumbres Lomas')], max_length=30),
        ),
    ]
